version: "3.4"
services:
  ui:
    container_name: k8s-handson-ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  api:
    container_name: k8s-handson-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  db:
    container_name: k8s-handson-db
    image: k8s-handson/db:v1
    build:
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env
