apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME
spec:
  selector:
    matchLabels:
      app: NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: NAME
    spec:
      containers:
        - name: ui
          image: 970527389096.dkr.ecr.ap-northeast-1.amazonaws.com/handson-ui:NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: NAME
spec:
  selector:
    app: NAME
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
