settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: backend
    path: .
    commands:
      install:
        status: true
        method: go build -o bin/main main.go db.go
      run:
        status: true
        method: ./bin/main
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
